builds:
- env:
  - CGO_ENABLED=0
before:
  hooks:
  - make
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
nfpm:
  maintainer: Alex Dzyoba <alex@dzyoba.com>
  homepage: https://github.com/alexdzyoba/tzconv
  description: Time converter with timezone fuzzy search
  license: MIT
  formats:
    - rpm
    - deb
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
